import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, Eye } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { Alert } from '../components/ui/Alert.jsx';
import { Card } from '../components/ui/Card.jsx';
import { LoadingState } from '../components/ui/LoadingState.jsx';
import { PageHeader } from '../components/ui/PageHeader.jsx';
import { StatusBadge } from '../components/ui/StatusBadge.jsx';
import { getApiError } from '../lib/api';
import { formatCurrency, formatDate } from '../lib/format';
import { groupApi } from '../services/groupApi';

export const MemberCyclesPage = () => { const { groupId } = useParams(); const [cycles, setCycles] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = useCallback(async () => { try { setCycles(await groupApi.myCycles(groupId)); } catch (loadError) { setError(getApiError(loadError, 'Unable to load your cycles.')); } finally { setLoading(false); } }, [groupId]); useEffect(() => { document.title = 'Pamoja | My Ajo cycles'; load(); }, [load]); if (loading) return <LoadingState label="Loading your cycles..." />; return <div className="space-y-5"><PageHeader eyebrow="Member workspace" title="My Ajo cycles" description="Your contribution history is separated by Ajo cycle." />{error && <Alert>{error}</Alert>}<div className="grid gap-4 lg:grid-cols-2">{cycles.map((cycle) => <Card key={cycle.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold text-pamoja-forest-deep">{cycle.name}</p><p className="mt-1 text-sm text-pamoja-muted">{cycle.frequency} · {formatCurrency(cycle.contributionAmount, cycle.currency)}</p><p className="mt-1 text-xs text-pamoja-muted">{formatDate(cycle.startDate)}{cycle.endDate ? ` – ${formatDate(cycle.endDate)}` : ''}</p></div><StatusBadge status={cycle.status === 'ACTIVE' ? 'success' : 'neutral'}>{cycle.status}</StatusBadge></div><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><p className="text-xs text-pamoja-muted">Paid</p><p className="mt-1 font-semibold">{formatCurrency(cycle.amountPaid, cycle.currency)}</p></div><div><p className="text-xs text-pamoja-muted">Outstanding</p><p className="mt-1 font-semibold text-pamoja-ochre">{formatCurrency(cycle.amountOutstanding, cycle.currency)}</p></div><div><p className="text-xs text-pamoja-muted">Progress</p><p className="mt-1 font-semibold">{cycle.progress}%</p></div></div><Link to={`/groups/${groupId}/cycles/${cycle.id}`} className="pamoja-focus mt-4 inline-flex min-h-10 items-center gap-2 rounded-lg bg-pamoja-forest px-3 text-sm font-semibold text-white"><Eye className="h-4 w-4" aria-hidden="true" />View cycle</Link></Card>)}{cycles.length === 0 && <Card className="p-5"><div className="flex items-center gap-3 text-sm text-pamoja-muted"><CalendarDays className="h-5 w-5" aria-hidden="true" />No cycle participation yet.</div></Card>}</div></div>; };
